# configs/default.yaml
wandb_project_name: "eclip-expert"

defaults:
  - _self_
  - data: data_default
  - hydra: hydra_default
  - model: model_default

seed: 42
learning_rate: 1e-4
batch_size: 32
max_steps: 500
max_length: 128
es_patience: 10
weight_decay: 1e-3
scheduler_name: "cosine" # or `plateau`
use_expert: False # switch between expert clip and base clip
naive_expert_fuse_method: False
geodesic_loss: False
dacl_on: False
clip_post_tune: False
fix_temperature: False
temperature: 0.07
xent_temperature: 0.4
aux_loss_proportion: 0.3
expert_min_prob: 0.05
expert_max_prob: 0.5
expert_cold_start_ratio: 0.1
expert_warmup_ratio: 0.3
expert_cooldown_ratio: 0.4
val_check_interval: 100
val_max_steps: None
limit_val_batches: 50
limit_train_batches: 50 # placeholder
num_epochs: 50 # placeholder, we use max_steps
num_gpus: 1
num_nodes: 1
num_workers: 4
precision: "16-mixed"
callbacks:
  save_checkpoint: True
  early_stop: True
  monitor_lr: True
exp_note: ""
